#!/usr/bin/env python3
"""Builds data/puzzles.full.json offline (no internet). Run: python3 tools/build_puzzles.py
Sources: Babel/CLDR (countries, languages, currencies, cities), matplotlib xkcd colours, Unicode emoji names,
hand-written seeds below (comma separated), and meaningful combos (flavour x dessert etc.). Add seeds freely."""
import json, re, unicodedata, itertools, os, sys
def clean(s):
    s = unicodedata.normalize('NFD', s); s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    s = re.sub(r'\(.*?\)', ' ', s).replace('-', ' ').replace("'", '')
    s = re.sub(r'[^A-Za-z ]', ' ', s); s = re.sub(r'\s+', ' ', s).strip().upper()
    w = s.split(' '); n = len(s.replace(' ', ''))
    if not s or len(w) > 4 or n < 4 or n > 25 or (len(w) == 1 and n > 15): return None
    return s
DB = {}
def add(cat, items):
    d = DB.setdefault(cat, {})
    for i in items:
        c = clean(i)
        if c: d[c] = 1
S = lambda t: [x.strip() for x in t.split(',') if x.strip()]
def combo(a, b, fmt='{} {}'): return [fmt.format(x, y) for x in S(a) for y in S(b)]

# ---- offline data sources
from babel import Locale
L = Locale('en')
add('COUNTRIES', [v for k, v in L.territories.items() if len(k) == 2 and k not in ('EU', 'UN', 'ZZ', 'XA', 'XB')])
add('LANGUAGES', [v for k, v in L.languages.items() if '_' not in k and len(k) <= 3])
add('CURRENCIES', [v for k, v in L.currencies.items()])
try:
    import zoneinfo
    add('WORLD CITIES', [z.split('/')[-1].replace('_', ' ') for z in zoneinfo.available_timezones() if '/' in z and not z.startswith(('Etc', 'US/', 'SystemV', 'Antarctica'))])
except Exception as e: print('tz', e)
import matplotlib.colors as mc
add('COLORS', [k.replace('xkcd:', '') for k in mc.XKCD_COLORS] + list(mc.CSS4_COLORS))
def emo(lo, hi): 
    out = []
    for cp in range(lo, hi + 1):
        try: out.append(unicodedata.name(chr(cp)).replace(' FACE', '').replace(' SIGN', ''))
        except ValueError: pass
    return out
add('ANIMALS', emo(0x1F400, 0x1F43E) + emo(0x1F980, 0x1F9AE) + emo(0x1F990, 0x1F9A2))
add('FOOD AND DRINK', emo(0x1F32D, 0x1F32F) + emo(0x1F345, 0x1F37F) + emo(0x1F950, 0x1F96B))

# ---- hand-written seeds
add('DINOSAURS', S("Tyrannosaurus Rex,Triceratops,Velociraptor,Stegosaurus,Brachiosaurus,Diplodocus,Allosaurus,Ankylosaurus,Spinosaurus,Pachycephalosaurus,Parasaurolophus,Iguanodon,Apatosaurus,Brontosaurus,Carnotaurus,Giganotosaurus,Compsognathus,Dilophosaurus,Gallimimus,Megalosaurus,Baryonyx,Deinonychus,Utahraptor,Microraptor,Archaeopteryx,Pteranodon,Plesiosaurus,Mosasaurus,Ichthyosaurus,Dimetrodon,Argentinosaurus,Therizinosaurus,Oviraptor,Protoceratops,Maiasaura,Edmontosaurus,Corythosaurus,Lambeosaurus,Styracosaurus,Centrosaurus,Kentrosaurus,Coelophysis,Herrerasaurus,Plateosaurus,Camarasaurus,Mamenchisaurus,Cryolophosaurus,Albertosaurus,Gorgosaurus,Ceratosaurus,Suchomimus,Irritator,Amargasaurus,Nigersaurus,Saltasaurus,Titanosaurus,Dreadnoughtus,Shunosaurus,Tuojiangosaurus,Psittacosaurus,Mononykus,Troodon,Sinosauropteryx,Yutyrannus,Dracorex,Stygimoloch,Sauropelta,Nodosaurus,Polacanthus,Minmi,Muttaburrasaurus,Leaellynasaura,Australovenator,Tarbosaurus,Alioramus,Daspletosaurus,Acrocanthosaurus,Torvosaurus,Majungasaurus,Abelisaurus,Rugops,Pyroraptor,Saurornitholestes,Gigantoraptor,Caudipteryx,Anchiornis,Confuciusornis,Quetzalcoatlus,Dimorphodon,Rhamphorhynchus,Liopleurodon,Kronosaurus,Elasmosaurus,Tylosaurus,Archelon,Deinosuchus,Sarcosuchus,Megalodon,Dunkleosteus,Hadrosaurus,Tenontosaurus,Hypsilophodon,Othnielia,Camptosaurus,Barosaurus,Supersaurus,Sauroposeidon,Puertasaurus,Patagotitan,Ultrasaurus,Seismosaurus"))
add('BIRDS', S("Eagle,Falcon,Sparrow,Penguin,Flamingo,Peacock,Pelican,Albatross,Hummingbird,Woodpecker,Kingfisher,Cockatoo,Parrot,Toucan,Ostrich,Emu,Cassowary,Kiwi,Owl,Hawk,Vulture,Condor,Osprey,Heron,Stork,Crane,Swan,Goose,Duck,Pigeon,Dove,Robin,Blue Jay,Cardinal,Starling,Magpie,Raven,Crow,Nightingale,Skylark,Swallow,Swift,Wren,Finch,Canary,Budgerigar,Macaw,Lorikeet,Kookaburra,Puffin,Seagull,Cormorant,Gannet,Pheasant,Quail,Partridge,Turkey,Peafowl,Hoopoe,Bee Eater,Roadrunner,Secretary Bird,Harpy Eagle,Bald Eagle,Golden Eagle,Barn Owl,Snowy Owl,Great Horned Owl,Rockhopper Penguin,Emperor Penguin,King Penguin,Blue Tit,Great Tit,Chaffinch,Goldfinch,Bullfinch,Oriole,Mockingbird,Bird of Paradise,Lyrebird,Hornbill,Shoebill,Spoonbill,Ibis,Egret,Bittern,Plover,Sandpiper,Curlew,Lapwing,Kestrel,Peregrine Falcon,Goshawk,Buzzard,Harrier,Kite,Frigatebird,Tern,Skua,Dodo,Weaver,Sunbird,Lovebird,Cockatiel,Quetzal,Trogon,Cuckoo,Nightjar,Whippoorwill,Grebe,Loon,Coot,Moorhen,Rail,Dipper,Nuthatch,Treecreeper,Bunting,Linnet,Siskin,Redstart,Wagtail,Pipit,Thrush,Blackbird,Warbler,Flycatcher,Shrike,Jay,Chough,Jackdaw,Rook,Bowerbird,Honeyeater"))
add('SEA CREATURES', S("Dolphin,Whale,Shark,Octopus,Squid,Jellyfish,Starfish,Seahorse,Sea Turtle,Manta Ray,Stingray,Clownfish,Angelfish,Pufferfish,Swordfish,Marlin,Tuna,Barracuda,Moray Eel,Electric Eel,Lobster,Crab,Shrimp,Prawn,Krill,Barnacle,Oyster,Clam,Mussel,Scallop,Abalone,Nautilus,Cuttlefish,Sea Urchin,Sea Cucumber,Sea Anemone,Coral,Sponge,Walrus,Seal,Sea Lion,Manatee,Dugong,Narwhal,Beluga,Orca,Humpback Whale,Blue Whale,Sperm Whale,Great White Shark,Hammerhead Shark,Whale Shark,Tiger Shark,Bull Shark,Mako Shark,Nurse Shark,Lionfish,Blobfish,Anglerfish,Oarfish,Sunfish,Flying Fish,Parrotfish,Surgeonfish,Triggerfish,Grouper,Snapper,Barramundi,Halibut,Flounder,Sole,Cod,Haddock,Herring,Sardine,Anchovy,Mackerel,Salmon,Trout,Sturgeon,Piranha,Catfish,Carp,Goldfish,Koi,Guppy,Betta,Hermit Crab,Horseshoe Crab,Spider Crab,King Crab,Sea Snake,Leatherback Turtle,Hawksbill Turtle,Giant Squid,Colossal Squid,Portuguese Man of War,Box Jellyfish,Sea Dragon,Pipefish,Remora,Wrasse,Goby,Blenny,Damselfish,Tang,Mahi Mahi,Wahoo,Sailfish"))
add('INSECTS', S("Butterfly,Moth,Beetle,Ladybug,Dragonfly,Damselfly,Grasshopper,Cricket,Locust,Mantis,Praying Mantis,Stick Insect,Cockroach,Termite,Ant,Bee,Wasp,Hornet,Bumblebee,Honeybee,Firefly,Mosquito,Housefly,Fruit Fly,Horsefly,Cicada,Aphid,Flea,Louse,Earwig,Mayfly,Lacewing,Weevil,Stag Beetle,Dung Beetle,Rhinoceros Beetle,Hercules Beetle,Goliath Beetle,Fire Ant,Army Ant,Leafcutter Ant,Carpenter Ant,Monarch Butterfly,Swallowtail,Luna Moth,Atlas Moth,Silkworm,Caterpillar,Tarantula,Scorpion,Centipede,Millipede,Black Widow,Wolf Spider,Jumping Spider,Trapdoor Spider,Tick,Mite,Water Strider,Backswimmer,Cranefly,Sawfly,Katydid,Leafhopper,Stinkbug,Assassin Bug,Bed Bug,Silverfish,Thrips,Antlion,Owlfly,Scarab,Blowfly,Hoverfly,Botfly,Tsetse Fly"))
add('DOG BREEDS', S("Labrador,Golden Retriever,German Shepherd,Bulldog,French Bulldog,Poodle,Beagle,Rottweiler,Dachshund,Boxer,Husky,Siberian Husky,Chihuahua,Pomeranian,Shih Tzu,Pug,Maltese,Yorkshire Terrier,Corgi,Great Dane,Doberman,Saint Bernard,Newfoundland,Mastiff,Bloodhound,Basset Hound,Greyhound,Whippet,Afghan Hound,Saluki,Borzoi,Collie,Border Collie,Sheepdog,Australian Shepherd,Cocker Spaniel,Springer Spaniel,Cavalier King Charles,Bichon Frise,Havanese,Lhasa Apso,Akita,Shiba Inu,Chow Chow,Samoyed,Malamute,Weimaraner,Vizsla,Pointer,Setter,Irish Setter,Airedale,Schnauzer,Scottish Terrier,West Highland Terrier,Jack Russell,Bull Terrier,Staffordshire,Pit Bull,Dalmatian,Bernese Mountain Dog,Pekingese,Papillon,Basenji,Ridgeback,Cane Corso,Belgian Malinois,Keeshond,Schipperke,Australian Cattle Dog,Bouvier,Leonberger,Pyrenees,Kuvasz,Komondor,Puli,Otterhound,Foxhound,Coonhound,Harrier,Lurcher,Tibetan Mastiff,Tibetan Terrier,Japanese Chin,Toy Poodle,Miniature Schnauzer,Boston Terrier,Affenpinscher,Brussels Griffon,Norwich Terrier,Cairn Terrier,Border Terrier,Welsh Terrier,Lakeland Terrier,Kerry Blue Terrier,Wolfhound,Deerhound,Sloughi,Ibizan Hound,Rhodesian Ridgeback,Chesapeake Bay Retriever,Flat Coated Retriever,Curly Coated Retriever,Nova Scotia Duck Tolling Retriever,Clumber Spaniel,Brittany,Pointer German Shorthaired"))
add('FAMOUS BRANDS', S("Apple,Samsung,Google,Microsoft,Amazon,Facebook,Instagram,Netflix,Spotify,YouTube,TikTok,Twitter,Snapchat,WhatsApp,Nike,Adidas,Puma,Reebok,Converse,Vans,Under Armour,New Balance,Skechers,Gucci,Prada,Chanel,Louis Vuitton,Hermes,Rolex,Cartier,Tiffany,Versace,Armani,Burberry,Dior,Fendi,Balenciaga,Zara,Uniqlo,Levis,Gap,Tommy Hilfiger,Ralph Lauren,Calvin Klein,Lacoste,Coca Cola,Pepsi,Sprite,Fanta,Red Bull,Monster Energy,Starbucks,McDonalds,Burger King,KFC,Subway,Dominos,Pizza Hut,Wendys,Taco Bell,Dunkin,Nestle,Cadbury,Hershey,Mars,Snickers,Kitkat,Oreo,Pringles,Lays,Doritos,Heinz,Kelloggs,Nutella,Toyota,Honda,Ford,Tesla,BMW,Mercedes Benz,Audi,Volkswagen,Porsche,Ferrari,Lamborghini,Nissan,Hyundai,Mazda,Volvo,Jaguar,Bentley,Rolls Royce,Sony,Panasonic,Toshiba,Nintendo,Playstation,Xbox,Intel,Nvidia,Dell,Lenovo,Asus,Huawei,Xiaomi,Oppo,Nokia,Motorola,LG,Canon,Nikon,Ikea,Lego,Disney,Pixar,Barbie,Hasbro,Mattel,Colgate,Pampers,Dove,Nivea,Loreal,Gillette,Pantene,Sunsilk,Lipton,Milo,Maggi,Tesco,Walmart,Costco,Target,Ebay,Alibaba,Shopee,Lazada,Grab,Uber,Airbnb,Paypal,Visa,Mastercard,Shell,Petronas,Caltex,Airasia,Emirates,Lufthansa,Boeing,Airbus,Hilton,Marriott,Adobe,Oracle,Intel Core,Zoom,Slack,Twitch,Pinterest,Reddit,Tinder,Duolingo,Canva,Shazam,Shopify,Samsonite,Tupperware,Duracell,Energizer,Casio,Seiko,Citizen,Swatch,Ray Ban,Oakley,Crocs,Havaianas,Timberland,Dr Martens,North Face,Patagonia,Columbia,Fila,Kappa,Umbro,Asics,Mizuno,Yonex,Wilson,Head,Speedo,Hello Kitty,Lays Chips,Twisties,Ovaltine,Horlicks,Pocari Sweat,Yakult,Calpis"))
add('CAR AND BIKE BRANDS', S("Toyota,Honda,Ford,Chevrolet,Tesla,Nissan,Mazda,Subaru,Suzuki,Mitsubishi,Lexus,Infiniti,Acura,Kia,Hyundai,Genesis,Peugeot,Renault,Citroen,Fiat,Alfa Romeo,Maserati,Lancia,Ferrari,Lamborghini,Bugatti,Pagani,McLaren,Aston Martin,Bentley,Rolls Royce,Jaguar,Land Rover,Range Rover,Mini,Lotus,Vauxhall,Volvo,Saab,Skoda,Seat,Opel,Porsche,Audi,Volkswagen,Mercedes,BMW,Cadillac,Buick,Dodge,Jeep,Chrysler,Lincoln,Ram,GMC,Hummer,Pontiac,Mustang,Corvette,Camaro,Harley Davidson,Ducati,Yamaha,Kawasaki,Triumph,Vespa,Piaggio,Royal Enfield,KTM,Aprilia,Indian,Norton,BSA,Proton,Perodua,Tata,Mahindra,Geely,Chery,BYD,Great Wall,Nio,Polestar,Rivian,Lucid,Smart,Daihatsu,Isuzu,Hino,Scania,Mack,Kenworth,Peterbilt"))
add('GEOGRAPHY', S("Amazon River,Nile,Mississippi,Yangtze,Danube,Rhine,Thames,Ganges,Mekong,Congo River,Volga,Euphrates,Tigris,Zambezi,Niger River,Murray River,Rio Grande,Colorado River,Yukon,Loire,Seine,Rhone,Tagus,Elbe,Oder,Vistula,Indus,Brahmaputra,Irrawaddy,Salween,Mount Everest,K2,Kilimanjaro,Mont Blanc,Matterhorn,Denali,Aconcagua,Elbrus,Fuji,Kinabalu,Vesuvius,Etna,Krakatoa,Mount Rushmore,Mount Olympus,Ben Nevis,Snowdon,Table Mountain,Sahara,Gobi,Kalahari,Atacama,Namib,Mojave,Arabian Desert,Thar Desert,Antarctica,Arctic,Pacific Ocean,Atlantic Ocean,Indian Ocean,Southern Ocean,Arctic Ocean,Mediterranean,Caribbean,Baltic Sea,North Sea,Red Sea,Black Sea,Caspian Sea,Dead Sea,South China Sea,Coral Sea,Lake Victoria,Lake Superior,Lake Baikal,Lake Titicaca,Lake Geneva,Lake Tanganyika,Lake Malawi,Lake Michigan,Loch Ness,Great Barrier Reef,Amazon Rainforest,Serengeti,Himalayas,Andes,Alps,Rocky Mountains,Pyrenees,Carpathians,Urals,Appalachians,Atlas Mountains,Tibetan Plateau,Great Rift Valley,Death Valley,Mariana Trench,Bermuda Triangle,Panama Canal,Suez Canal,Strait of Gibraltar,Cape of Good Hope,Cape Horn,Iceland,Greenland,Madagascar,Borneo,Sumatra,Java,Sulawesi,Tasmania,Hawaii,Galapagos,Maldives,Seychelles,Fiji,Tahiti,Bali,Sicily,Sardinia,Corsica,Crete,Cyprus,Malta,Ireland,Equator,Tropic of Cancer,Prime Meridian,Latitude,Longitude,Continent,Peninsula,Archipelago,Delta,Glacier,Tundra,Savanna,Steppe,Canyon,Plateau,Volcano,Geyser,Fjord,Lagoon,Atoll,Isthmus,Estuary,Waterfall"))
add('SPORTS', S("Football,Soccer,Basketball,Baseball,Tennis,Badminton,Table Tennis,Volleyball,Handball,Rugby,Cricket,Hockey,Ice Hockey,Golf,Swimming,Diving,Water Polo,Rowing,Canoeing,Kayaking,Sailing,Surfing,Windsurfing,Skiing,Snowboarding,Skating,Figure Skating,Speed Skating,Curling,Bobsled,Luge,Skateboarding,Cycling,BMX,Mountain Biking,Athletics,Marathon,Sprinting,Hurdles,High Jump,Long Jump,Pole Vault,Shot Put,Discus,Javelin,Decathlon,Triathlon,Gymnastics,Trampoline,Weightlifting,Powerlifting,Bodybuilding,Boxing,Wrestling,Judo,Karate,Taekwondo,Kung Fu,Muay Thai,Fencing,Archery,Shooting,Equestrian,Polo,Squash,Racquetball,Lacrosse,Softball,Netball,Sepak Takraw,Pickleball,Bowling,Billiards,Snooker,Darts,Chess,Rock Climbing,Bouldering,Parkour,Sumo,Aikido,Capoeira,Kabaddi,Formula One,Motocross,Rally,Drag Racing,Karting,Horse Racing,Camel Racing,Dragon Boat,Paragliding,Skydiving,Bungee Jumping,Scuba Diving,Snorkeling,Fishing,Hiking,Orienteering,Ultimate Frisbee,Dodgeball,Kickboxing,Cross Country,Biathlon,Ski Jumping,Slalom,Curling Stone,Hammer Throw"))
add('MUSICAL INSTRUMENTS', S("Piano,Guitar,Violin,Cello,Viola,Double Bass,Harp,Flute,Piccolo,Clarinet,Oboe,Bassoon,Saxophone,Trumpet,Trombone,Tuba,French Horn,Cornet,Bugle,Drums,Snare Drum,Bass Drum,Timpani,Xylophone,Marimba,Vibraphone,Glockenspiel,Cymbals,Triangle,Tambourine,Maracas,Castanets,Bongos,Congas,Djembe,Tabla,Sitar,Sarod,Veena,Erhu,Guzheng,Pipa,Koto,Shamisen,Gamelan,Angklung,Sape,Gong,Kompang,Rebana,Ukulele,Banjo,Mandolin,Lute,Harpsichord,Organ,Accordion,Harmonica,Bagpipes,Recorder,Ocarina,Panpipes,Didgeridoo,Kalimba,Theremin,Synthesizer,Keyboard,Electric Guitar,Bass Guitar,Steel Drum,Cowbell,Zither,Balalaika,Bouzouki,Oud,Dulcimer,Celesta,Melodica,Kazoo,Whistle,Conch Shell,Alphorn,Shofar,Sousaphone,Flugelhorn,Euphonium,Contrabassoon,English Horn,Bass Clarinet,Fiddle,Hurdy Gurdy,Cajon,Bodhran,Tin Whistle,Concertina,Pan Flute,Jaw Harp"))
add('FRUITS', S("Apple,Banana,Orange,Mango,Pineapple,Papaya,Guava,Lychee,Rambutan,Mangosteen,Durian,Jackfruit,Starfruit,Dragon Fruit,Passion Fruit,Pomegranate,Watermelon,Cantaloupe,Honeydew,Grapes,Strawberry,Blueberry,Raspberry,Blackberry,Cranberry,Gooseberry,Mulberry,Cherry,Peach,Nectarine,Plum,Apricot,Pear,Kiwi,Fig,Date,Persimmon,Lemon,Lime,Grapefruit,Pomelo,Tangerine,Mandarin,Clementine,Kumquat,Coconut,Avocado,Tamarind,Soursop,Custard Apple,Longan,Salak,Langsat,Sapodilla,Breadfruit,Quince,Elderberry,Boysenberry,Loganberry,Currant,Damson,Greengage,Ackee,Feijoa,Loquat,Jujube,Cempedak,Ciku,Duku,Pitaya,Yuzu,Bergamot,Citron,Blood Orange,Cape Gooseberry,Physalis,Acai,Goji Berry,Bilberry,Huckleberry,Cloudberry,Lingonberry,Rose Apple,Water Apple,Santol,Marang,Noni,Kiwano,Sugar Apple,Mamey,Cherimoya,Jabuticaba,Pawpaw,Miracle Fruit"))
add('VEGETABLES', S("Carrot,Potato,Tomato,Onion,Garlic,Ginger,Spinach,Lettuce,Cabbage,Broccoli,Cauliflower,Celery,Cucumber,Pumpkin,Squash,Zucchini,Eggplant,Brinjal,Okra,Ladyfinger,Capsicum,Chilli,Jalapeno,Pepper,Corn,Peas,Green Beans,Long Beans,Kale,Bok Choy,Choy Sum,Kangkung,Water Spinach,Bean Sprouts,Radish,Turnip,Beetroot,Parsnip,Sweet Potato,Yam,Cassava,Taro,Lotus Root,Bamboo Shoots,Mushroom,Asparagus,Artichoke,Leek,Shallot,Spring Onion,Chives,Fennel,Kohlrabi,Brussels Sprouts,Watercress,Arugula,Rocket,Endive,Radicchio,Chard,Collard Greens,Butternut,Bitter Gourd,Winter Melon,Luffa,Snake Gourd,Bottle Gourd,Edamame,Chickpea,Lentil,Soybean,Tempeh,Tofu,Seaweed,Daikon,Rutabaga,Celeriac,Horseradish,Wasabi,Turmeric,Galangal,Lemongrass,Curry Leaf,Basil,Mint,Coriander,Parsley,Dill,Oregano,Thyme,Rosemary,Sage"))
add('FLOWERS AND PLANTS', S("Rose,Tulip,Daisy,Sunflower,Lily,Orchid,Jasmine,Lotus,Hibiscus,Bougainvillea,Frangipani,Marigold,Chrysanthemum,Carnation,Daffodil,Lavender,Violet,Pansy,Poppy,Peony,Iris,Lilac,Magnolia,Camellia,Azalea,Rhododendron,Hydrangea,Gardenia,Petunia,Zinnia,Dahlia,Begonia,Geranium,Cosmos,Snapdragon,Foxglove,Bluebell,Buttercup,Dandelion,Clover,Edelweiss,Lily of the Valley,Cherry Blossom,Sakura,Wisteria,Fuchsia,Anemone,Aster,Freesia,Gladiolus,Hyacinth,Amaryllis,Cactus,Aloe Vera,Bamboo,Fern,Moss,Ivy,Palm,Bonsai,Venus Flytrap,Pitcher Plant,Rafflesia,Water Lily,Oak,Maple,Pine,Cedar,Birch,Willow,Elm,Banyan,Baobab,Redwood,Sequoia,Eucalyptus,Mahogany,Teak,Ebony,Cypress,Spruce,Fir,Ash,Beech,Poplar,Mangrove,Rubber Tree,Coconut Palm,Date Palm,Sago Palm,Monstera,Snake Plant,Spider Plant,Peace Lily,Jade Plant,Succulent,Sensitive Plant,Bird of Paradise,Ginger Flower,Torch Ginger,Ylang Ylang,Champaca,Lemon Balm,Chamomile,Echinacea,Ginseng"))
add('SUPERHEROES', S("Superman,Batman,Spider Man,Iron Man,Captain America,Thor,Hulk,Black Widow,Hawkeye,Black Panther,Doctor Strange,Ant Man,Wasp,Captain Marvel,Scarlet Witch,Vision,Falcon,Winter Soldier,Wonder Woman,Aquaman,The Flash,Green Lantern,Cyborg,Supergirl,Batgirl,Robin,Nightwing,Catwoman,Wolverine,Cyclops,Storm,Rogue,Gambit,Beast,Nightcrawler,Jean Grey,Professor X,Deadpool,Daredevil,Punisher,Luke Cage,Iron Fist,Jessica Jones,Silver Surfer,Human Torch,Mister Fantastic,Invisible Woman,The Thing,Star Lord,Gamora,Drax,Rocket Raccoon,Groot,Nebula,Shazam,Green Arrow,Martian Manhunter,Hawkgirl,Blue Beetle,Booster Gold,Static Shock,Spawn,Hellboy,Ghost Rider,Blade,Moon Knight,Shang Chi,Ms Marvel,She Hulk,Squirrel Girl,Nova,Quicksilver,Mr Incredible,Elastigirl,Frozone,Invincible,Homelander,Starlight,Hancock,Big Hero Six,Kick Ass,Mighty Mouse,Powerpuff Girls,Astro Boy,Ultraman,Kamen Rider,Saitama,All Might,Deku,Megaman,Sonic,Tails,Knuckles,Shadow"))
add('MYTHOLOGY', S("Zeus,Hera,Poseidon,Hades,Athena,Apollo,Artemis,Ares,Aphrodite,Hephaestus,Hermes,Demeter,Dionysus,Persephone,Hestia,Eros,Pan,Prometheus,Atlas,Cronus,Rhea,Gaia,Uranus,Hercules,Perseus,Theseus,Achilles,Odysseus,Jason,Orpheus,Medusa,Minotaur,Cerberus,Hydra,Chimera,Sphinx,Pegasus,Centaur,Cyclops,Satyr,Siren,Harpy,Gorgon,Phoenix,Griffin,Unicorn,Dragon,Kraken,Leviathan,Odin,Thor,Loki,Freya,Frigg,Baldur,Tyr,Heimdall,Fenrir,Valkyrie,Yggdrasil,Asgard,Valhalla,Ragnarok,Ra,Osiris,Isis,Horus,Anubis,Set,Thoth,Bastet,Sekhmet,Hathor,Sobek,Ptah,Amun,Jupiter,Juno,Neptune,Pluto,Minerva,Mars,Venus,Mercury,Vulcan,Diana,Vesta,Ceres,Bacchus,Cupid,Janus,Saturn,Shiva,Vishnu,Brahma,Ganesha,Hanuman,Kali,Lakshmi,Saraswati,Durga,Krishna,Rama,Sita,Indra,Agni,Amaterasu,Susanoo,Izanagi,Kitsune,Tengu,Kappa,Oni,Naga,Garuda,Barong,Quetzalcoatl,Kukulkan,Tezcatlipoca,Huitzilopochtli,Anansi,Banshee,Leprechaun,Selkie,Basilisk,Golem,Vampire,Werewolf,Yeti,Bigfoot,Chupacabra,Mothman,Nessie,Excalibur,King Arthur,Merlin,Lancelot,Guinevere,Camelot,Avalon,Morgan le Fay,Beowulf,Grendel,Sisyphus,Tantalus,Icarus,Daedalus,Narcissus,Echo,Pandora,Midas,Helen of Troy,Paris,Hector,Priam,Cassandra,Ariadne,Medea,Circe,Calypso,Penelope,Telemachus,Aeneas,Romulus,Remus"))
add('SCIENCE', S("Atom,Molecule,Electron,Proton,Neutron,Quark,Photon,Gravity,Magnetism,Electricity,Energy,Momentum,Velocity,Acceleration,Friction,Inertia,Thermodynamics,Entropy,Relativity,Quantum,Wavelength,Frequency,Amplitude,Spectrum,Prism,Lens,Mirror,Laser,Radiation,Isotope,Ion,Catalyst,Enzyme,Protein,Chromosome,Genome,Gene,DNA,RNA,Cell,Nucleus,Mitochondria,Chloroplast,Photosynthesis,Respiration,Evolution,Ecosystem,Habitat,Food Chain,Herbivore,Carnivore,Omnivore,Predator,Species,Fossil,Mineral,Igneous,Sedimentary,Metamorphic,Earthquake,Tsunami,Volcano,Tectonic Plates,Atmosphere,Ozone,Climate,Hurricane,Tornado,Monsoon,Rainbow,Eclipse,Solar System,Orbit,Comet,Asteroid,Meteor,Nebula,Supernova,Pulsar,Quasar,Big Bang,Dark Matter,Black Hole,Microscope,Telescope,Thermometer,Barometer,Compass,Periodic Table,Acid,Alkali,Solvent,Solution,Compound,Element,Mixture,Evaporation,Condensation,Fusion,Fission,Oxidation,Combustion,Hypothesis,Experiment,Theory,Variable,Newton,Einstein,Darwin,Galileo,Curie,Tesla,Pasteur,Faraday,Kepler,Copernicus,Hawking,Mendel,Edison"))
add('SPACE', S("Sun,Moon,Mercury,Venus,Earth,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto,Ceres,Eris,Io,Europa,Ganymede,Callisto,Titan,Enceladus,Triton,Phobos,Deimos,Charon,Milky Way,Andromeda,Orion,Big Dipper,Little Dipper,Polaris,North Star,Sirius,Betelgeuse,Rigel,Vega,Antares,Proxima Centauri,Alpha Centauri,Cassiopeia,Scorpius,Sagittarius,Cygnus,Pegasus Constellation,Ursa Major,Ursa Minor,Leo,Taurus,Gemini,Cancer,Virgo,Libra,Aquarius,Pisces,Aries,Capricorn,Halley Comet,Hubble,Voyager,Apollo,Challenger,Columbia,Discovery,Endeavour,Atlantis,Sputnik,Gagarin,Armstrong,Buzz Aldrin,Neil Armstrong,Sally Ride,Space Shuttle,Space Station,Rocket,Satellite,Astronaut,Cosmonaut,Spacesuit,Launch Pad,Lunar Module,Mars Rover,Curiosity,Perseverance,Spirit,Opportunity,Pathfinder,Cassini,Galileo Probe,Juno Probe,New Horizons,James Webb,Kepler Telescope,Asteroid Belt,Kuiper Belt,Oort Cloud,Solar Flare,Sunspot,Corona,Aurora,Galaxy,Nebula,Black Hole,Wormhole,Supernova,Exoplanet,Light Year,Orbit,Gravity,Zero Gravity,Crater,Lunar Eclipse,Solar Eclipse,Full Moon,New Moon,Crescent Moon,Blood Moon,Meteor Shower,Shooting Star"))
add('CAPITAL CITIES', S("Kuala Lumpur,Putrajaya,Singapore,Jakarta,Bangkok,Hanoi,Manila,Phnom Penh,Vientiane,Naypyidaw,Bandar Seri Begawan,Dili,Beijing,Tokyo,Seoul,Pyongyang,Ulaanbaatar,Taipei,New Delhi,Islamabad,Dhaka,Colombo,Kathmandu,Thimphu,Male,Kabul,Tehran,Baghdad,Riyadh,Doha,Abu Dhabi,Muscat,Kuwait City,Manama,Amman,Beirut,Damascus,Jerusalem,Ankara,Tbilisi,Yerevan,Baku,Tashkent,Astana,Bishkek,Dushanbe,Ashgabat,Moscow,Kyiv,Minsk,Warsaw,Prague,Vienna,Budapest,Bratislava,Berlin,Bern,Paris,Brussels,Amsterdam,Luxembourg,London,Dublin,Edinburgh,Cardiff,Madrid,Lisbon,Rome,Athens,Sofia,Bucharest,Belgrade,Zagreb,Ljubljana,Sarajevo,Skopje,Tirana,Podgorica,Vilnius,Riga,Tallinn,Helsinki,Stockholm,Oslo,Copenhagen,Reykjavik,Valletta,Nicosia,Cairo,Tripoli,Tunis,Algiers,Rabat,Khartoum,Addis Ababa,Nairobi,Kampala,Kigali,Dodoma,Lusaka,Harare,Pretoria,Cape Town,Windhoek,Gaborone,Maputo,Antananarivo,Luanda,Kinshasa,Brazzaville,Libreville,Yaounde,Abuja,Accra,Dakar,Bamako,Ouagadougou,Niamey,Ottawa,Washington,Mexico City,Havana,Kingston,Nassau,Panama City,San Jose,Bogota,Caracas,Quito,Lima,La Paz,Santiago,Buenos Aires,Montevideo,Asuncion,Brasilia,Canberra,Wellington,Suva,Port Moresby,Apia,Nukualofa"))
add('LANDMARKS', S("Eiffel Tower,Big Ben,Colosseum,Pyramids of Giza,Great Wall of China,Taj Mahal,Statue of Liberty,Sydney Opera House,Leaning Tower of Pisa,Burj Khalifa,Petronas Towers,Machu Picchu,Christ the Redeemer,Golden Gate Bridge,Mount Rushmore,Niagara Falls,Stonehenge,Angkor Wat,Parthenon,Times Square,Empire State Building,Buckingham Palace,Tower Bridge,London Eye,Louvre,Arc de Triomphe,Notre Dame,Versailles,Sagrada Familia,Alhambra,Brandenburg Gate,Neuschwanstein,Red Square,Kremlin,Hagia Sophia,Blue Mosque,Petra,Forbidden City,Terracotta Army,Tokyo Tower,Gateway of India,Golden Temple,Victoria Falls,Table Mountain,Uluru,Ayers Rock,Sphinx,Abu Simbel,Karnak,Borobudur,Prambanan,Bagan,Wat Arun,Grand Palace,Marina Bay Sands,Merlion,Batu Caves,Twin Towers,Menara KL,Kinabalu Park,Sultan Abdul Samad,Putra Mosque,Penang Hill,Malacca Fort,Historic Malacca,Hoover Dam,Space Needle,Alcatraz,Brooklyn Bridge,White House,Capitol Hill,Lincoln Memorial,Grand Canyon,Yellowstone,Yosemite,Hollywood Sign,Las Vegas Strip,Chichen Itza,Teotihuacan,Easter Island,Iguazu Falls,Sugarloaf Mountain,Galata Tower,Cappadocia,Pamukkale,Meteora,Acropolis,Santorini,Mont Saint Michel,Chateau de Chambord,Cinque Terre,Trevi Fountain,Spanish Steps,Vatican City,Sistine Chapel,Saint Peters Basilica,Rialto Bridge,Doges Palace,Duomo,Ponte Vecchio,Atomium,Manneken Pis,Windmills of Kinderdijk,Anne Frank House,Little Mermaid,Tivoli Gardens,Blue Lagoon,Northern Lights,Fjords of Norway,Prague Castle,Charles Bridge,Schonbrunn Palace,Belvedere,Matterhorn Peak,Jungfrau,Cliffs of Moher,Giants Causeway,Edinburgh Castle,Tower of London,Windsor Castle,Hadrians Wall,Bath Abbey,Blackpool Tower"))
add('MOVIES AND CARTOONS', S("Titanic,Avatar,Frozen,Moana,Encanto,Coco,Up,Cars,Toy Story,Finding Nemo,Finding Dory,Monsters Inc,Ratatouille,Wall E,Inside Out,Brave,Tangled,Aladdin,The Lion King,Mulan,Pocahontas,Cinderella,Snow White,Sleeping Beauty,Beauty and the Beast,The Little Mermaid,Bambi,Dumbo,Pinocchio,Peter Pan,Alice in Wonderland,The Jungle Book,101 Dalmatians,Shrek,Madagascar,Kung Fu Panda,How to Train Your Dragon,Ice Age,Despicable Me,Minions,Zootopia,Big Hero Six,Wreck It Ralph,Lilo and Stitch,Hercules,Tarzan,Harry Potter,The Lord of the Rings,The Hobbit,Star Wars,Star Trek,Jurassic Park,Jurassic World,Jaws,Back to the Future,The Matrix,Inception,Interstellar,Gladiator,Braveheart,Forrest Gump,The Godfather,Goodfellas,Scarface,Casablanca,Gone with the Wind,Wizard of Oz,Mary Poppins,The Sound of Music,Grease,Ghostbusters,Home Alone,Mrs Doubtfire,Jumanji,Men in Black,Independence Day,Terminator,Alien,Predator,Rocky,Rambo,Die Hard,Top Gun,Mission Impossible,James Bond,Skyfall,Casino Royale,Pirates of the Caribbean,Transformers,Fast and Furious,Avengers,Black Panther,Spider Man,Batman Begins,The Dark Knight,Joker,Wonder Woman,Aquaman,Barbie,Oppenheimer,Parasite,Squid Game,Money Heist,Stranger Things,Breaking Bad,Game of Thrones,Friends,The Office,Seinfeld,Simpsons,Family Guy,South Park,SpongeBob,Tom and Jerry,Looney Tunes,Scooby Doo,Pokemon,Doraemon,Naruto,One Piece,Dragon Ball,Sailor Moon,Spirited Away,Totoro,Ben 10,Peppa Pig,Paw Patrol,Bluey,Upin Ipin,BoBoiBoy,Ejen Ali,Pada Zaman Dahulu,Mr Bean,Kungfu Hustle,Crazy Rich Asians,Everything Everywhere All at Once,The Lion Witch and the Wardrobe,Narnia,Charlie and the Chocolate Factory,Willy Wonka,Matilda,Coraline,Kubo,Paddington,Wallace and Gromit,Shaun the Sheep,Chicken Run"))
add('FAMOUS PEOPLE', S("Albert Einstein,Isaac Newton,Marie Curie,Leonardo da Vinci,Michelangelo,Picasso,Van Gogh,Monet,Rembrandt,Salvador Dali,Frida Kahlo,Andy Warhol,Shakespeare,Charles Dickens,Mark Twain,Jane Austen,Agatha Christie,Ernest Hemingway,Tolkien,JK Rowling,Roald Dahl,Dr Seuss,Mozart,Beethoven,Bach,Chopin,Tchaikovsky,Elvis Presley,The Beatles,Michael Jackson,Madonna,Prince,Bob Marley,Freddie Mercury,David Bowie,Taylor Swift,Beyonce,Rihanna,Adele,Ed Sheeran,Lady Gaga,Katy Perry,Justin Bieber,Ariana Grande,Billie Eilish,Bruno Mars,Shakira,Siti Nurhaliza,P Ramlee,Michelle Yeoh,Jackie Chan,Bruce Lee,Jet Li,Tom Hanks,Leonardo DiCaprio,Brad Pitt,Johnny Depp,Will Smith,Denzel Washington,Morgan Freeman,Robert De Niro,Al Pacino,Marilyn Monroe,Audrey Hepburn,Charlie Chaplin,Walt Disney,Steven Spielberg,Alfred Hitchcock,Stan Lee,Steve Jobs,Bill Gates,Elon Musk,Mark Zuckerberg,Jeff Bezos,Warren Buffett,Henry Ford,Thomas Edison,Nikola Tesla,Alexander Graham Bell,Wright Brothers,Stephen Hawking,Charles Darwin,Galileo,Aristotle,Plato,Socrates,Confucius,Buddha,Gandhi,Nelson Mandela,Martin Luther King,Abraham Lincoln,George Washington,Winston Churchill,Napoleon,Julius Caesar,Cleopatra,Alexander the Great,Genghis Khan,Queen Victoria,Queen Elizabeth,Princess Diana,Mother Teresa,Neil Armstrong,Yuri Gagarin,Christopher Columbus,Marco Polo,Ferdinand Magellan,Cristiano Ronaldo,Lionel Messi,Pele,Maradona,Neymar,David Beckham,Michael Jordan,LeBron James,Kobe Bryant,Serena Williams,Roger Federer,Rafael Nadal,Usain Bolt,Muhammad Ali,Mike Tyson,Tiger Woods,Lewis Hamilton,Michael Schumacher,Lee Chong Wei,Datuk Lee,Nicol David,Mohd Farhan"))
add('JOBS AND PROFESSIONS', S("Doctor,Nurse,Surgeon,Dentist,Pharmacist,Veterinarian,Teacher,Professor,Lecturer,Principal,Engineer,Architect,Lawyer,Judge,Accountant,Banker,Cashier,Clerk,Secretary,Manager,Director,Programmer,Developer,Designer,Animator,Photographer,Journalist,Reporter,Editor,Writer,Author,Poet,Actor,Actress,Singer,Musician,Dancer,Painter,Sculptor,Carpenter,Plumber,Electrician,Mechanic,Welder,Builder,Bricklayer,Farmer,Fisherman,Butcher,Baker,Chef,Waiter,Barista,Bartender,Barber,Hairdresser,Tailor,Cobbler,Jeweler,Pilot,Flight Attendant,Captain,Sailor,Driver,Taxi Driver,Bus Driver,Train Driver,Police Officer,Firefighter,Soldier,Detective,Security Guard,Postman,Librarian,Scientist,Chemist,Biologist,Physicist,Astronomer,Astronaut,Geologist,Archaeologist,Historian,Economist,Psychologist,Therapist,Counselor,Social Worker,Politician,Mayor,Diplomat,Ambassador,Astrologer,Magician,Clown,Comedian,Athlete,Coach,Referee,Lifeguard,Gardener,Florist,Cleaner,Janitor,Miner,Lumberjack,Blacksmith,Potter,Weaver,Cartographer,Translator,Interpreter,Auctioneer,Realtor,Salesman,Merchant,Trader,Entrepreneur,Consultant,Auditor,Paramedic,Midwife,Optician,Radiologist,Pediatrician,Cardiologist,Dermatologist,Neurologist,Anesthetist,Chiropractor,Physiotherapist,Nutritionist,Zookeeper,Beekeeper,Shepherd,Cowboy,Ranger,Herbalist,Barrister,Notary,Paralegal,Actuary,Statistician,Data Scientist,Hacker,Blogger,YouTuber,Streamer,Influencer"))
add('BODY PARTS', S("Head,Forehead,Eyebrow,Eyelash,Eyelid,Eyeball,Pupil,Nose,Nostril,Mouth,Lips,Tongue,Teeth,Gums,Jaw,Chin,Cheek,Ear,Earlobe,Neck,Throat,Shoulder,Armpit,Arm,Elbow,Forearm,Wrist,Hand,Palm,Finger,Thumb,Knuckle,Fingernail,Chest,Rib,Ribcage,Spine,Back,Waist,Stomach,Belly Button,Hip,Thigh,Knee,Kneecap,Calf,Shin,Ankle,Foot,Heel,Toe,Toenail,Sole,Brain,Heart,Lungs,Liver,Kidney,Bladder,Spleen,Pancreas,Intestine,Colon,Appendix,Esophagus,Trachea,Skull,Femur,Tibia,Fibula,Humerus,Radius,Ulna,Clavicle,Scapula,Pelvis,Sternum,Vertebra,Muscle,Tendon,Ligament,Cartilage,Skin,Hair,Blood,Vein,Artery,Nerve,Cornea,Retina,Eardrum,Tonsils,Diaphragm,Biceps,Triceps,Hamstring,Abdomen,Torso,Temple,Nape,Sole of Foot,Big Toe,Pinky,Index Finger,Middle Finger,Ring Finger,Bone Marrow,Gallbladder,Thyroid,Adrenal Gland"))
add('CLOTHING AND FASHION', S("Shirt,T Shirt,Blouse,Sweater,Hoodie,Jacket,Blazer,Coat,Raincoat,Trench Coat,Cardigan,Vest,Jeans,Trousers,Shorts,Skirt,Dress,Gown,Suit,Tuxedo,Jumpsuit,Overalls,Pajamas,Nightgown,Bathrobe,Swimsuit,Bikini,Underwear,Socks,Stockings,Tights,Leggings,Scarf,Gloves,Mittens,Hat,Cap,Beanie,Beret,Fedora,Turban,Hijab,Tudung,Songkok,Kebaya,Baju Kurung,Baju Melayu,Sarong,Batik,Sari,Kimono,Yukata,Hanbok,Cheongsam,Qipao,Kurta,Dashiki,Poncho,Kilt,Tie,Bow Tie,Belt,Suspenders,Cufflinks,Sneakers,Sandals,Slippers,Flip Flops,Boots,Loafers,High Heels,Stilettos,Sunglasses,Handbag,Backpack,Wallet,Umbrella,Necklace,Bracelet,Earrings,Ring,Brooch,Watch,Tiara,Crown,Corset,Petticoat,Apron,Uniform,Lab Coat,Cape,Cloak,Shawl,Bandana,Headband,Visor,Helmet,Raincoat Poncho,Denim Jacket,Bomber Jacket,Leather Jacket,Windbreaker,Tracksuit,Sweatpants,Polo Shirt,Tank Top,Crop Top,Culottes,Palazzo Pants,Cargo Pants,Chinos,Bermuda Shorts"))
add('HOUSEHOLD OBJECTS', S("Table,Chair,Sofa,Couch,Bed,Pillow,Blanket,Mattress,Wardrobe,Cupboard,Bookshelf,Desk,Lamp,Curtain,Carpet,Rug,Mirror,Clock,Television,Refrigerator,Freezer,Microwave,Oven,Stove,Kettle,Toaster,Blender,Rice Cooker,Air Fryer,Dishwasher,Washing Machine,Dryer,Vacuum Cleaner,Iron,Fan,Air Conditioner,Heater,Telephone,Remote Control,Router,Charger,Flashlight,Candle,Matches,Lighter,Broom,Mop,Bucket,Dustpan,Sponge,Soap,Shampoo,Toothbrush,Toothpaste,Towel,Toilet,Sink,Bathtub,Shower,Faucet,Plate,Bowl,Cup,Mug,Glass,Fork,Spoon,Knife,Chopsticks,Ladle,Spatula,Whisk,Colander,Frying Pan,Saucepan,Wok,Cutting Board,Peeler,Grater,Can Opener,Bottle Opener,Corkscrew,Teapot,Thermos,Lunch Box,Trash Can,Basket,Hanger,Ladder,Hammer,Screwdriver,Wrench,Pliers,Saw,Drill,Tape Measure,Scissors,Stapler,Glue,Tape,Pencil,Eraser,Ruler,Notebook,Calculator,Envelope,Stamp,Umbrella Stand,Doormat,Doorbell,Key,Padlock,Fire Extinguisher,Smoke Detector,First Aid Kit,Thermometer,Scale,Comb,Hairdryer,Razor,Nail Clipper,Tweezers,Needle,Thread,Button,Zipper,Safety Pin,Coat Rack,Shoe Rack,Picture Frame,Vase,Ashtray,Piggy Bank"))
add('TRANSPORT', S("Car,Bus,Truck,Van,Taxi,Motorcycle,Scooter,Bicycle,Tricycle,Train,Tram,Monorail,Subway,Metro,Bullet Train,Locomotive,Airplane,Helicopter,Jet,Glider,Hot Air Balloon,Airship,Blimp,Drone,Rocket,Spaceship,Ship,Boat,Ferry,Yacht,Canoe,Kayak,Raft,Sailboat,Speedboat,Cruise Ship,Submarine,Tugboat,Cargo Ship,Aircraft Carrier,Hovercraft,Jet Ski,Gondola,Rickshaw,Tuk Tuk,Sampan,Junk,Dhow,Ambulance,Fire Engine,Police Car,Tractor,Bulldozer,Excavator,Crane,Forklift,Steamroller,Dump Truck,Cement Mixer,Tank,Jeep,Limousine,Convertible,Sports Car,Pickup Truck,Minivan,Caravan,Trailer,Go Kart,Skateboard,Roller Skates,Segway,Cable Car,Funicular,Chairlift,Elevator,Escalator,Sled,Sleigh,Horse Carriage,Camel,Ox Cart,Wheelbarrow,Wheelchair,Stroller,Unicycle,Pedicab,Trolley Bus,Double Decker,School Bus,Airport Shuttle,Space Shuttle,Lunar Rover"))
add('WEATHER AND NATURE', S("Rain,Drizzle,Shower,Thunderstorm,Lightning,Thunder,Snow,Sleet,Hail,Blizzard,Frost,Fog,Mist,Haze,Smog,Cloud,Rainbow,Sunshine,Sunrise,Sunset,Twilight,Dawn,Dusk,Breeze,Wind,Gale,Storm,Hurricane,Typhoon,Cyclone,Tornado,Monsoon,Drought,Flood,Heatwave,Cold Snap,Humidity,Temperature,Forecast,Barometer,Isobar,Cumulus,Stratus,Cirrus,Nimbus,Aurora Borealis,Eclipse,Avalanche,Landslide,Wildfire,Earthquake,Tsunami,Volcanic Eruption,Waterspout,Whirlwind,Sandstorm,Dust Devil,Dew,Puddle,Icicle,Snowflake,Snowman,Igloo,Glacier,Iceberg,Tide,Wave,Current,Waterfall,Stream,Pond,Meadow,Forest,Jungle,Rainforest,Swamp,Marsh,Cave,Cliff,Beach,Coast,Reef,Island,Valley,Hill,Mountain,Desert,Oasis,Prairie,Savannah,Woodland,Orchard,Garden,Field"))
add('BOARD AND VIDEO GAMES', S("Chess,Checkers,Monopoly,Scrabble,Clue,Cluedo,Risk,Battleship,Connect Four,Jenga,Uno,Twister,Trivial Pursuit,Pictionary,Taboo,Catan,Carcassonne,Ticket to Ride,Pandemic,Dominion,Mahjong,Go,Backgammon,Ludo,Snakes and Ladders,Congkak,Dam Haji,Chinese Checkers,Domino,Poker,Blackjack,Bridge,Solitaire,Rummy,Tetris,Pac Man,Space Invaders,Pong,Mario,Super Mario,Zelda,Metroid,Donkey Kong,Kirby,Pokemon Go,Minecraft,Roblox,Fortnite,Among Us,Fall Guys,Candy Crush,Angry Birds,Subway Surfers,Temple Run,Flappy Bird,Clash of Clans,Clash Royale,Mobile Legends,PUBG,Free Fire,Genshin Impact,League of Legends,Dota,Counter Strike,Valorant,Overwatch,Apex Legends,Call of Duty,Halo,Gears of War,Grand Theft Auto,Red Dead Redemption,Assassins Creed,Far Cry,Fifa,Pro Evolution Soccer,Madden,NBA 2K,Gran Turismo,Need for Speed,Mario Kart,Street Fighter,Tekken,Mortal Kombat,Sonic the Hedgehog,Crash Bandicoot,Spyro,Rayman,Pikmin,Animal Crossing,Stardew Valley,Terraria,The Sims,SimCity,Civilization,Age of Empires,Starcraft,Warcraft,Diablo,Skyrim,Fallout,Witcher,Dark Souls,Elden Ring,Cyberpunk,Portal,Half Life,Doom,Quake,Resident Evil,Silent Hill,Final Fantasy,Dragon Quest,Kingdom Hearts,Persona,Bioshock,Hades Game,Celeste,Hollow Knight,Cuphead,Undertale,Fez,Limbo,Inside"))
# ---- meaningful combinations (each result is a real, sensible name)
FL = "Strawberry,Chocolate,Vanilla,Mango,Banana,Blueberry,Coconut,Lemon,Orange,Peach,Cherry,Raspberry,Caramel,Coffee,Mint,Pistachio,Hazelnut,Almond,Honey,Ginger,Pineapple,Apple,Pumpkin,Cinnamon,Matcha,Durian,Taro,Lychee,Passion Fruit,Blackcurrant,Cheese,Peanut Butter,Maple,Butterscotch,Toffee,Red Velvet,Oreo,Rose,Cranberry,Mocha"
add('SWEETS AND DESSERTS', combo(FL, "Cake,Cupcake,Ice Cream,Cheesecake,Pudding,Muffin,Donut,Cookie,Brownie,Milkshake,Smoothie,Sorbet,Tart,Pie,Macaron,Jelly,Popsicle,Lollipop,Fudge,Truffle,Mousse,Crepe,Waffle,Pancake,Custard,Parfait,Sundae,Gelato,Cookie Dough,Candy", '{} {}'))
add('SWEETS AND DESSERTS', S("Apple Pie,Banana Split,Tiramisu,Baklava,Churros,Cendol,Kuih Lapis,Onde Onde,Pulut Hitam,Bubur Cha Cha,Ais Kacang,Halwa,Gulab Jamun,Mochi,Dorayaki,Pavlova,Creme Brulee,Eclair,Profiterole,Cotton Candy,Marshmallow,Gingerbread,Jelly Beans,Gummy Bears,Rock Candy,Candy Cane,Bubblegum,Nougat,Marzipan,Turkish Delight,Panna Cotta,Cannoli,Souffle,Trifle,Cobbler,Strudel,Danish Pastry,Croissant,Cinnamon Roll,Doughnut,Beignet,Zabaglione,Flan,Kulfi,Rasmalai,Jalebi,Tang Yuan,Egg Tart,Mooncake,Dango,Taiyaki"))
MAIN = "Rice,Noodles,Fried Rice,Burger,Pizza,Pasta,Sandwich,Salad,Soup,Curry,Stew,Sushi,Tacos,Burrito,Omelette,Sausage,Wings,Steak,Dumplings,Wrap,Pie,Skewers,Porridge,Stir Fry"
add('FOOD AND DRINK', combo("Chicken,Beef,Lamb,Pork,Fish,Prawn,Squid,Crab,Egg,Cheese,Mushroom,Vegetable,Tofu,Spicy,Garlic,Butter,Teriyaki,Sambal,Satay,Tomato,Lemon Herb,Honey Mustard,Black Pepper,BBQ,Coconut,Thai,Korean,Japanese,Italian,Mexican,Indian,Malay,Vietnamese,Greek", MAIN))
add('FOOD AND DRINK', S("Nasi Lemak,Roti Canai,Satay,Laksa,Char Kuey Teow,Rendang,Mee Goreng,Nasi Goreng,Teh Tarik,Cendol,Rojak,Curry Mee,Bak Kut Teh,Hokkien Mee,Wantan Mee,Dim Sum,Peking Duck,Pad Thai,Tom Yum,Pho,Banh Mi,Kimchi,Bibimbap,Ramen,Tempura,Takoyaki,Paella,Lasagna,Risotto,Ratatouille,Goulash,Falafel,Hummus,Shawarma,Kebab,Biryani,Tandoori,Naan,Samosa,Guacamole,Nachos,Quesadilla,Fish and Chips,Hot Dog,Fried Chicken,Mac and Cheese,French Toast,Bagel,Pretzel,Popcorn,Peanut Butter,Maple Syrup,Green Tea,Bubble Tea,Iced Coffee,Hot Chocolate,Lemonade,Orange Juice,Coconut Water,Sugarcane Juice,Milk Tea,Espresso,Cappuccino,Latte,Mojito,Smoothie Bowl"))


# ---- keep every category at 100+ puzzles: fold small ones into related bigger ones
add('MUSICAL INSTRUMENTS', S("Lyre,Sackbut,Serpent,Cornett,Shawm,Crumhorn,Rebec,Viol,Theorbo,Clavichord,Spinet,Fortepiano,Harmonium,Ondes Martenot,Waterphone,Glass Harmonica,Rainstick,Guiro,Claves,Cabasa,Vibraslap,Woodblock,Temple Block,Tubular Bells,Steelpan"))
add('TRANSPORT', S("Snowmobile,Bobsleigh,Dune Buggy,Quad Bike,Moped,Minibus,Coach,Lorry,Barge,Catamaran,Trawler,Icebreaker,Paddle Steamer,Longboat,Outrigger,Rowing Boat,Lifeboat,Ambulance Helicopter,Biplane,Seaplane,Space Capsule,Maglev,Steam Engine,Freight Train,Night Train"))
MERGE = {'INSECTS': 'ANIMALS', 'CAR AND BIKE BRANDS': 'FAMOUS BRANDS', 'FRUITS': 'FRUITS AND VEGETABLES', 'VEGETABLES': 'FRUITS AND VEGETABLES', 'WEATHER AND NATURE': 'GEOGRAPHY'}
for a, b in MERGE.items():
    if a in DB: DB.setdefault(b, {}).update(DB.pop(a))

# ---- WORD POWER: real dictionary words (5-12 letters), grouped by first letter (the category name is a clue for viewers)
BAD_PRE = ('fuck','shit','cunt','whore','nigg','fagg','bitch','slut','rapist','dildo','penis','vagina','porn','tits','boob','pussy','pussie','bastard','asshole','wank','twat','retard','kike','chink','spick','tranny')
BAD = set('rape raped rapes raping sexy sexed sexes dicks cocks damned crappy piss pissed negro negroes gooks dyke dykes homos queers whores arse asses bugger buggers'.split())
words = set()
for l in open('/usr/share/hunspell/en_US.dic', encoding='utf-8', errors='ignore').read().split('\n')[1:]:
    w = l.split('/')[0].strip()
    if re.fullmatch(r'[a-z]{5,12}', w) and w not in BAD and not w.startswith(BAD_PRE): words.add(w)
by = {}
for w in sorted(words): by.setdefault(w[0].upper(), []).append(w)
small = sorted(k for k, v in by.items() if len(v) < 300)
for k, v in by.items():
    if k not in small: DB['WORDS STARTING WITH ' + k] = {x.upper(): 1 for x in v}
if small: DB['WORDS STARTING WITH ' + ', '.join(small[:-1]) + ' OR ' + small[-1]] = {x.upper(): 1 for k in small for x in by[k]}
print({k: len(v) for k, v in DB.items()})
OUT = {k: sorted(v) for k, v in DB.items()}
tot = sum(len(v) for v in OUT.values()); print('categories', len(OUT), 'puzzles', tot)
os.makedirs('data', exist_ok=True)
json.dump(OUT, open('data/puzzles.full.json', 'w'), separators=(',', ':'))
